services:
  - type: web
    name: estudiante
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: estudiante_service/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg://universidad_xxe6_user:cBuBRdbD9FdUXR8XWmEJwsIlVRflzjso@dpg-d2nmglumcj7s73cp3vgg-a.oregon-postgres.render.com:5432/universidad_xxe6?sslmode=require

  - type: web
    name: carrera
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: carrera_service/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg://universidad_xxe6_user:cBuBRdbD9FdUXR8XWmEJwsIlVRflzjso@dpg-d2nmglumcj7s73cp3vgg-a.oregon-postgres.render.com:5432/universidad_xxe6?sslmode=require

  - type: web
    name: facultad
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: facultad_service/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: postgresql+psycopg://universidad_xxe6_user:cBuBRdbD9FdUXR8XWmEJwsIlVRflzjso@dpg-d2nmglumcj7s73cp3vgg-a.oregon-postgres.render.com:5432/universidad_xxe6?sslmode=require

  - type: web
    name: gateway
    env: docker
    plan: free
    rootDir: .
    dockerfilePath: gateway/Dockerfile
    autoDeploy: true
    envVars:
      - key: ESTUDIANTES_URL
        value: https://estudiante-kib6.onrender.com
      - key: CARRERAS_URL
        value: https://carrera-ello.onrender.com
      - key: FACULTADES_URL
        value: https://facultad-n4qi.onrender.com
