name: feature → testing (60%+)

on:
  push:
    branches-ignore:
      - master
      - testing
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ci-merge-testing:
    runs-on: ubuntu-latest
    concurrency:
      group: automerge-testing
      cancel-in-progress: false

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: universidad
          MARIADB_USER: fastapi
          MARIADB_PASSWORD: 1234
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s --health-timeout=5s --health-retries=10

    env:
      DATABASE_URL: mysql+pymysql://fastapi:1234@127.0.0.1:3306/universidad
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
